server:
  port: 7002
eureka:
  instance:
    hostname: eureka-server2.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server1.com:7001/eureka,http://eureka-server3.com:7003/eureka
